### ISSUE TITLE
Confusing documentation - config.neon

### ISSUE THREAD

**Issue by Grez** [Zenify/DoctrineMigrations#10]
`enabled: FALSE # cli based loading; set TRUE to force loading in non-cli`

Actual behaviour:
  FALSE: extension is disabled everywhere
  TRUE: extension is enabled everywhere
  Parameter not set: enabled only in CLI

I didn't quite get that from the #comment. It might be nice to make it more clearer :)

**Comment by TomasVotruba** [comment]
Thanks for feedback. Could you send PR with more clear description?

**Comment by Grez** [comment]
Is there any case where it would be useful to disable the extension via ``enabled: FALSE``? It does basically the same thing as if you'd delete the extension from config, doesn't it?

If that is so, I'd change the property to `cliONLY` with values `TRUE|FALSE` (`TRUE` as default)

**Comment by TomasVotruba** [comment]
Unfortunately, I don't remember the use case ATM.

I plan to decouple extension from Router and Kdyby\Doctrine in near future.
I think I can include this change in it.
