### ISSUE TITLE
Add option suppressing NoMigrationsToExecute exception

### ISSUE THREAD

**Issue by janedbal** [Zenify/DoctrineMigrations#19]
Every time I deploy, I would like to run migration script that checks if some changes were made (and migrate if needed). Currently, when no migration is available I get an exception.

There might be some option to catch this exception and just output that no migrations were executed:

```sh
php www/index.php migrations:migrate --no-interaction --allow-empty-migration
```

What do you think?

**Comment by janedbal** [comment]
Well, this seems to happen only for the first time when migration table is empty. Anyway, I think that this should behave in the same way (just output "No migrations to execute.") no matter if some migrations were previously executed. The exception seems useless to me, or is it not?

**Comment by TomasVotruba** [comment]
Thanks for your suggestion. I think this is issue rather for https://github.com/doctrine/migrations repository. Since this package only integrates this to Nette\DI.

I'd suggest try there first. It seems like good idea!

**Comment by janedbal** [comment]
Seems like it is fixed in [doctrine/migrations v1.1](https://github.com/doctrine/migrations/releases/tag/v1.1.0)

**Comment by TomasVotruba** [comment]
@janedbal Thanks for update. Can you confirmed by trying out?

**Comment by janedbal** [comment]
@TomasVotruba confirmed

**Comment by TomasVotruba** [comment]
Thank!
