### ISSUE TITLE
Unable to run command from code

### ISSUE THREAD

**Issue by wodCZ** [Zenify/DoctrineMigrations#21]
Hello,

at first, thank You for this extension!

Now, 
I think that after [this commit](https://github.com/Zenify/DoctrineMigrations/commit/bd61d88b5184067579c05e0ab2161e431a2c2782) it is not possible to run commands this way:

```php
$command   = $this->container->getByType(\Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand::class);
$helperSet = $this->container->getByType(\Symfony\Component\Console\Helper\HelperSet::class);

$input = new ArrayInput([]);
$input->setInteractive(FALSE);
$output = new StringOutput();
$command->setHelperSet($helperSet);
$status = $command->run($input, $output);
```

because `ConsoleEvents::COMMAND` event is not fired.

I'm not sure if I'm running it right. Also that helperSet is some king of workaround (not sure why it was needed).
My use case is InstallPresenter in my system, where in one step I run migrations this way.

Also I've had problem running it in cli, because I had Symnedi Events extension registered before Kdyby Events extension. After moving Symnedi AFTER Kdyby, migrations showed up in cli command. 

As a "workaround", I reverted back to 2.2.2 where everything works as expected.

**Comment by TomasVotruba** [comment]
Hey, thanks for reporting.

> Also I've had problem running it in cli, because I had Symnedi Events extension registered before Kdyby Events extension. After moving Symnedi AFTER Kdyby, migrations showed up in cli command.

This is the issue. I shall look on that first.

**Comment by wodCZ** [comment]
I've been told that prefered way to run command is this:
```
$input = new ArrayInput(['command' => 'migrations:migrate']);
$input->setInteractive(FALSE);
$output = new StringOutput();

$status = $this->consoleApp->run($input, $output);
```

but now I get `$status = 4` and output:
```
Loading configuration from the integration code of your framework (setter).
                                                                    
                    Doctrine Database Migrations           
```
and no migrations are executed. 

Again, when running command from cli, migrations run properly.

[Screenshot with code, output and event extension panel](http://i.imgur.com/0ZqzpBS.png), if it helps.

**Comment by TomasVotruba** [comment]
Btw, what version do you use? Last 2.3?

**Comment by wodCZ** [comment]
Yes, 2.3.0.

**Comment by TomasVotruba** [comment]
What exact error happens on command run in console?

**Comment by wodCZ** [comment]
From console, everything is OK.
Using code snippet above, migrations do not run (are not detected) probably because event `ConsoleEvents::COMMAND` is not fired, so availabe migrations are not lazy loaded.

**Comment by TomasVotruba** [comment]
I see.

**Comment by TomasVotruba** [comment]
Just curious, why would you run console command out of console scope?
Do you write test for something?

**Comment by wodCZ** [comment]
I have web based installer which takes care of creating config file, database schema, admin user and default data.

**Comment by TomasVotruba** [comment]
Hey, I've added manual test: https://github.com/Zenify/DoctrineMigrations/blob/4e4e34fd6580c683ac20b3b51ddb7074c7674f12/tests/ManualUsageTest.php and it passes well now.

I forgot to bind Symfony\EventDispatcher to Symfony\Console, thus the whole bug.

Could you try last tagged version: 2.3.2?

**Comment by wodCZ** [comment]
Works great!

Everything is OK now, thank You @TomasVotruba!

**Comment by TomasVotruba** [comment]
@wodCZ I'm glad. Happy to help!
