### ISSUE TITLE
Unable to load migrations file

### ISSUE THREAD

**Issue by TomasPilaru** [Zenify/DoctrineMigrations#23]
Hi,

in latest release is unable load migration files by `migrations:migrate` command. Doctrine\Migrations didn't trigger Console event so your `RegisterMigrationsEventSubscriber` didn't register migration files into configuration class.

**Comment by TomasVotruba** [comment]
Hey, thanks for reporting.

This should be solved via: https://github.com/Zenify/DoctrineMigrations/issues/21#issuecomment-151659145

**Comment by TomasVotruba** [comment]
Ping, is this issue still on?

**Comment by TomasPilaru** [comment]
Hi, sorry for late response. 
No, it's fixed.

**Comment by TomasVotruba** [comment]
Great! Thank you
