### ISSUE TITLE
Update symnedi/event-dispatcher

### ISSUE THREAD

**Issue by Vrtak-CZ** [Zenify/DoctrineMigrations#26]
Is it possible update `symnedi/event-dispatcher` to `~0.4.0` and release new version? After that we can use this package with Nette 2.4+.

**Comment by enumag** [comment]
Can you try dev-master and confirm there are no problems?

**Comment by Vrtak-CZ** [comment]
Looks like it works OK (master - a56c8e8)

**Comment by enumag** [comment]
Thank you. I've tagged version 2.3.4 for you. I'll probably soon release 2.4 though.

**Comment by Vrtak-CZ** [comment]
Thank you!

**Comment by Vrtak-CZ** [comment]
I'm so sory but it does not work :-( Because there is still dependency for `^0.3.1`. It worked because there is no error but now i have error and problem with PHP 7.0 compatability is back.

**Comment by Vrtak-CZ** [comment]
There is line from composer documentation:

> For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`.

**Comment by enumag** [comment]
Not sure how it worked for you previously with the master branch - it shouldn't have. Anyway try 2.3.5. Thank you!
