### ISSUE TITLE
Rollback?

### ISSUE THREAD

**Issue by landsman** [Zenify/DoctrineMigrations#31]
1) Zaskočilo mě, že pokud dojde v rámci migrace k SQL chybě neprovede se rollback celé migrace zpět. To jsem předpokládal, že nastane, když to pracuje s Doctrine. V metodě "up" jsem použil více krát $this->addSql(); pro větší přehlednost, ale to doufám vliv nemá.

2) metoda "postUp" slouží k odpálení SQL po metodě "up" chápu to správně? Mám problem s tím, že neprovede. V konzoli její SQL není, v databázi beze změn.

**Comment by enumag** [comment]
Pokud vím tak ALTER TABLE migracím nepodléhá tzn. rollback by nic nevyřešil.

PostUp je tuším pro věci co chceš udělat ručně - do konzole se nic nevypíše. Ale že by to neproběhlo vůbec se mi nezdá.

**Comment by landsman** [comment]
@enumag ALTER TABLE tam mám poměrně hodně. Ono to nepracuje ve smyslu nějakého uložení původních hodnot? Prostý backup všech tabulek, které byly ovlivněny a jejich rollback zpět ze zálohy v případě chyby by úplně stačil.

**Comment by enumag** [comment]
Nestačil protože ne všechny databáze umí vypnout foreing key check. Tzn při pokusu o obnovu jen části tabulek bys narazil na to že je kvůli cizím klíčům nemůžeš smazat.

Ne v postUp se to dělá jinak: http://jcfiala.net/blog/2014/08/29/using-doctrine-migrations-part-2-adding-data-migration

**Comment by landsman** [comment]
Rozumim, tzn. by bylo třeba backupovat, rollbackovat cele tabulky & jejich vazby. Tak mě napadá, není tam nějaké "hooky" / eventy, kam bych si mohl strčit kompletní backup, po migraci zkontrolovat chyby, vratit backup?

**Comment by enumag** [comment]
I kdyby, osobně bych to přes ně nedělal. Stačí si napsat nějaký vlastní skript který

- vytvoří zálohu
- pustí migrace
- při nenulovém exit code obnoví zálohu

**Comment by landsman** [comment]
Jasný, stejně to bude součástí nějakého deployment scriptu, tak to dává smysl.

**Comment by enumag** [comment]
Akorát pozor že pokud selžou ty migrace tak bys měl ideálně revetnout i deployment kódu. Nový kód se starou db většinou fungovat nebude.

**Comment by landsman** [comment]
To je jasne. Jak zjistim ze exit nebyl null?

**Comment by enumag** [comment]
No to záleží v čem ten skript píšeš. V shell skriptu se myslím použije `||`.

**Comment by landsman** [comment]
Ano shell script. Diky, vyzkousim.

Jeste badam, zda $this->addSql() funguje jako pridani do nejakeho pole. 
V metode Up ji pouzivam vice krat a nektere query se neprovedou, ale ani nezahlasi chybu.
